# Copyright 2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

inherit multilib toolchain-funcs

DESCRIPTION="Fungw manages dynamic function calls across different programming languages"
HOMEPAGE="http://repo.hu/projects/fungw/"
IUSE="perl"
SRC_URI="http://repo.hu/projects/fungw/releases/${P}.tar.gz"

LICENSE="LGPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="perl? ( dev-lang/perl[ithreads] )"
RDEPEND="${DEPEND}"
BDEPEND=""

# TODO: Add use flags for the other supported languages and disable them if the use flag
# 		isn't set (see how it's done with perl). This is only done with perl because the
# 		package fails to compile without ithreads support in perl.
src_prepare() {
	eapply_user

	# Disable perl support if requested
	if ! use perl; then
		sed -i -e 's/require(.*perl.*);//g' libfungwbind/scconfig_hooks.h ||
			die 'Failed to disable perl support!'
	fi
}

src_configure() {
	# This is NOT autotools
	./configure 2>&1 \
		--prefix="${EPREFIX}/usr" \
		--libdirname="$(get_libdir)" \
		--CC="$(tc-getCC)" \
		--CFLAGS="${CFLAGS}" \
		--LDFLAGS="${LDFLAGS}" \
		$([[ -n $CTARGET ]] && echo -n "--target=${CTARGET}") \
	| tee "${T}/configure.log" || die "Configure failed!"

	# Replace "cd <dir> && make all" expressions with GNU Make "$(MAKE) -C <dir> all"
	# expressions. This allows for parallel compilations, and is required after
	# ./configure since some of the Makefiles are autogenerated with a custom autotools
	# replacement that I haven't bothered to understand fully yet.
	find . -name Makefile -print0 |
		xargs -0 -n 1 sed -i -e 's/cd \([a-zA-Z0-9_]*\) && make \([a-zA-Z0-9_]*\)/$(MAKE) -C \1 \2/g' ||
		die 'Failed to fix the Makefiles!'

	# Install docs to a better location. Again, this could probably done more cleanly
	# if I understood better how their autotools replacement worked.
	sed -i -e "s:DOCDIR=\\(.*\\)$:DOCDIR=\1/${P}:g" ./doc/Makefile
}

src_install() {
	dodir "/usr/share/doc/${P}"
	emake DESTDIR="${D}" install
}

pkg_postinst() {
	elog "$(awk '/fungw configuration summary/ {p=1} p==1' "${T}/configure.log")"
	elog "If you require support for additional scripting languages post installation,"
	elog "you must recompile manually with 'emerge -1 ${CATEGORY}/${PN}' after merging"
	elog "the new languages. Adding perl support will also require that the perl use"
	elog "flag is added."
}
